- name: Fail if CONTAINER_RUNTIME is not set to podman
  fail:
    msg: Only Podman is supported in CentOS/RHEL8
  when: CONTAINER_RUNTIME != "podman"
- name: Enable SELinux
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  become: true
  when: ansible_selinux.status == "enabled"
- name: Remove any previous tripleo-repos to avoid version conflicts
  dnf:
    name: python*-tripleo-repos
    state: absent
  become: true
- name: Upgrade all packages
  dnf:
    name: '*'
    state: latest
    nobest: 'true'
  become: true
- name: Install podman
  dnf:
    name: podman
    state: present
  become: true
  when: CONTAINER_RUNTIME == "podman"
